version: "3.8"
services:

  jupyterhub:
    image: laihub/test
    build: .
    ports:
      - 8888:8888
    expose:
      - "8888"
    volumes:
      - /opt/jupyterhub/jupyterhub:/srv/jupyterhub

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro